server:
  port: 7070

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/backend_template"
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #you can set your time zone and format
  jackson:
    time-zone: Asia/Tashkent
    date-format: yyyy-MM-dd HH:mm:ss

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:7070/login/oauth2/code/google
            client-id: CLIENT_ID
            client-secret: CLIENT_SECRET
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo


secret:
  jwt:
    key:
      access: KEY_ACCESS
      refresh: KEY_REFRESH
    expiration:
      access: 600_000
      refresh: 604_800_000